apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: server-inventory
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mattang-e/server-inventory-k8s.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: server-inventory

  syncPolicy:
    automated:
      selfHeal: true